#!/usr/bin/env bash
# Concatenates base.css plus the named layers (in the order given) into
# src/css/custom.css. Usage:
#
#   ./themes/apply.sh b-middle cool l4-slate hybrid s3 d4
#
# Always starts from base.css. Fails loudly if a named layer doesn't exist.
# Backs up the pre-existing src/css/custom.css once, on first run.

set -euo pipefail

THEMES_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$THEMES_DIR/.." && pwd)"
TARGET="$REPO_ROOT/src/css/custom.css"
ORIGINAL_BACKUP="$THEMES_DIR/custom.css.original"
BASE="$THEMES_DIR/base.css"

if [ ! -f "$BASE" ]; then
  echo "error: $BASE not found" >&2
  exit 1
fi

layer_paths=("$BASE")

for name in "$@"; do
  path="$THEMES_DIR/$name.css"
  if [ ! -f "$path" ]; then
    echo "error: no such theme layer '$name' (expected $path)" >&2
    exit 1
  fi
  layer_paths+=("$path")
done

if [ ! -f "$ORIGINAL_BACKUP" ] && [ -f "$TARGET" ]; then
  cp "$TARGET" "$ORIGINAL_BACKUP"
  echo "backed up existing $TARGET -> $ORIGINAL_BACKUP"
fi

mkdir -p "$(dirname "$TARGET")"

{
  echo "/* GENERATED by themes/apply.sh. Do not edit directly. */"
  echo "/* recipe: base $* */"
  for path in "${layer_paths[@]}"; do
    echo
    echo "/* ---- $(basename "$path") ---- */"
    cat "$path"
  done
} > "$TARGET"

echo "recipe: base $*"
echo "wrote $TARGET"
