// Minimal stand-in for PROS's top-level api.h. Real PROS projects get this
// generated by the kernel template; EZ-Template's own headers just
// `#include "api.h"` and expect the whole pros:: surface (Motor, Imu,
// Controller, competition, ...) to already be visible by the time they're
// parsed, the same way the real one works. This just pulls in every stub
// pros/*.hpp so any include order EZ-Template's headers use resolves.
#pragma once

#include <cstdint>
#include <limits>

#include "pros/adi.hpp"
#include "pros/device.hpp"
#include "pros/imu.hpp"
#include "pros/misc.h"
#include "pros/misc.hpp"
#include "pros/motor_group.hpp"
#include "pros/motors.h"
#include "pros/motors.hpp"
#include "pros/rotation.hpp"
#include "pros/rtos.hpp"
#include "pros/screen.hpp"
#include "pros/usd.hpp"

#define PROS_ERR (INT32_MAX)
#define PROS_ERR_F (std::numeric_limits<double>::infinity())
