#!/bin/sh
# Writes include/EZ-Template/version.hpp from VERSION in the Makefile, and keeps
# the root "version" file in step with it. The Makefile runs this every time it is parsed, so
# nobody needs to run it by hand: to change the version, change VERSION in the Makefile.
# Usage: sh tools/gen-version.sh [version [output path]]
# With no version it reads VERSION from the root Makefile. With an output path it only writes
# that one file. Prints nothing on success, an error message on failure. Always exits 0: the
# Makefile treats any output as an error, and a bad version never touches an existing file.
root="$(dirname "$0")/.."
if [ $# -eq 0 ]; then
  v=$(sed -n 's/^VERSION:=//p' "$root/Makefile" | head -n 1 | tr -d '\r')
else
  v="$1"
fi
out="${2:-$root/include/EZ-Template/version.hpp}"

# Semver build metadata (4.0.0-beta.2+3f9a1c) isn't part of the version. LemLib/pros-build
# rewrites VERSION in the Makefile to add +<commit> before it runs make template.
v="${v%%+*}"

core="${v%%-*}"
pre=""; [ "$core" != "$v" ] && pre="${v#*-}"

IFS=. read -r major minor patch extra <<END
$core
END
for n in "$major" "$minor" "$patch"; do
  case "$n" in ''|*[!0-9]*) echo "VERSION '$v' is not MAJOR.MINOR.PATCH[-stage.N]"; exit 0;; esac
done
[ -n "$extra" ] && { echo "VERSION '$v' has too many dots"; exit 0; }

stage_name="${pre%%.*}"; num="${pre#*.}"
[ "$num" = "$pre" ] && num=""
# A dash with no stage, like 4.0.0- or 4.0.0-.1
[ "$core" != "$v" ] && [ -z "$stage_name" ] && { echo "VERSION '$v': prerelease must be alpha.N, beta.N or rc.N"; exit 0; }
case "$stage_name" in
  "")    stage=RELEASE; num=0 ;;
  alpha) stage=ALPHA ;;
  beta)  stage=BETA ;;
  rc)    stage=RC ;;
  *) echo "VERSION '$v': prerelease must be alpha.N, beta.N or rc.N"; exit 0 ;;
esac
case "$num" in ''|*[!0-9]*) echo "VERSION '$v': prerelease needs a number, like beta.2"; exit 0;; esac
# The numbers are pasted into #defines, where 010 would be read as octal and 08 wouldn't parse.
for n in "$major" "$minor" "$patch" "$num"; do
  case "$n" in 0?*) echo "VERSION '$v': no leading zeros in '$n'"; exit 0;; esac
done
for n in "$minor" "$patch" "$num"; do
  [ "$n" -gt 99 ] && { echo "VERSION '$v': minor, patch and prerelease number must be under 100"; exit 0; }
done

tmp="$out.tmp"
cat > "$tmp" <<HPP
// GENERATED by tools/gen-version.sh from VERSION in the Makefile. Do not edit.
// To change the version, change VERSION in the Makefile and run make.
#pragma once

/**
 * EZ-Template version macros, for libraries that support more than one
 * EZ-Template version.
 *
 * These were added in 4.0.0. EZ-Template 3.x has none of them, so your code has
 * to cope with them being missing.
 *
 * Check whether an API exists (prereleases count, so 4.0.0-beta.2 passes). Include
 * EZ-Template first, then give 3.x a fallback:
 * \code{.cpp}
 * #include "EZ-Template/api.hpp"  // before the fallback below
 *
 * #ifndef EZ_TEMPLATE_VERSION_AT_LEAST
 * #define EZ_TEMPLATE_VERSION_AT_LEAST(major, minor, patch) 0  // 3.x
 * #endif
 *
 * #if EZ_TEMPLATE_VERSION_AT_LEAST(4, 0, 0)
 *   // 4.0 or newer
 * #else
 *   // 3.x
 * #endif
 * \endcode
 *
 * Don't write "#if defined(EZ_TEMPLATE_VERSION_MAJOR) && EZ_TEMPLATE_VERSION_AT_LEAST(4, 0, 0)".
 * The preprocessor still parses the second half on 3.x, where that macro doesn't
 * exist, and stops with a syntax error.
 *
 * Check for an exact version, including the prerelease stage. Same idea, so nest the #if:
 * \code{.cpp}
 * #ifdef EZ_TEMPLATE_VERSION
 * #if EZ_TEMPLATE_VERSION >= EZ_TEMPLATE_VERSION_ENCODE(4, 0, 0, EZ_TEMPLATE_STAGE_RC, 1)
 *   // 4.0.0-rc.1 or newer
 * #endif
 * #endif
 * \endcode
 *
 * Alpha, beta and rc releases are not final. APIs can change or be removed between
 * them, and the final release may differ from any prerelease. EZ_TEMPLATE_VERSION_AT_LEAST
 * is true on every prerelease of that version, so if your code depends on something that
 * changed during the prereleases, compare against a specific stage as above. To be told
 * when you are building against a prerelease:
 * \code{.cpp}
 * #ifdef EZ_TEMPLATE_VERSION_STAGE
 * #if EZ_TEMPLATE_VERSION_STAGE != EZ_TEMPLATE_STAGE_RELEASE
 * #warning "Built against an EZ-Template prerelease, the API may change"
 * #endif
 * #endif
 * \endcode
 *
 * Print it:
 * \code{.cpp}
 * printf("EZ-Template %s\\n", EZ_TEMPLATE_VERSION_STRING);
 * \endcode
 *
 * Stages sort alpha < beta < rc < release, so 4.0.0-rc.1 < 4.0.0.
 * Minor, patch and the prerelease number must stay under 100.
 */

#define EZ_TEMPLATE_STAGE_ALPHA 0
#define EZ_TEMPLATE_STAGE_BETA 1
#define EZ_TEMPLATE_STAGE_RC 2
#define EZ_TEMPLATE_STAGE_RELEASE 3

#define EZ_TEMPLATE_VERSION_MAJOR $major
#define EZ_TEMPLATE_VERSION_MINOR $minor
#define EZ_TEMPLATE_VERSION_PATCH $patch
#define EZ_TEMPLATE_VERSION_STAGE EZ_TEMPLATE_STAGE_$stage
#define EZ_TEMPLATE_VERSION_PRERELEASE_NUM $num  // 0 on a full release
#define EZ_TEMPLATE_VERSION_PRERELEASE "$pre"  // "" on a full release
#define EZ_TEMPLATE_VERSION_STRING "$v"

// One integer that sorts correctly, alpha < beta < rc < release.
#define EZ_TEMPLATE_VERSION_ENCODE(major, minor, patch, stage, num) \\
  ((major) * 10000000L + (minor) * 100000L + (patch) * 1000L + (stage) * 100L + (num))
#define EZ_TEMPLATE_VERSION                                                  \\
  EZ_TEMPLATE_VERSION_ENCODE(EZ_TEMPLATE_VERSION_MAJOR, EZ_TEMPLATE_VERSION_MINOR, \\
                             EZ_TEMPLATE_VERSION_PATCH, EZ_TEMPLATE_VERSION_STAGE, \\
                             EZ_TEMPLATE_VERSION_PRERELEASE_NUM)

// Feature check. Ignores prerelease, so 4.0.0-beta.2 counts as 4.0.0.
#define EZ_TEMPLATE_VERSION_AT_LEAST(major, minor, patch)                    \\
  (EZ_TEMPLATE_VERSION >= EZ_TEMPLATE_VERSION_ENCODE(major, minor, patch, EZ_TEMPLATE_STAGE_ALPHA, 0))
HPP

# Only replace the file if it changed, so the build doesn't recompile everything.
if cmp -s "$tmp" "$out"; then rm -f "$tmp"; else mv "$tmp" "$out"; fi

# The root "version" file (nothing reads it) follows VERSION, so there is one place to bump.
# Only when writing the real header, and only if the file exists, so deleting it is all it
# takes to stop maintaining it.
if [ -z "$2" ] && [ -f "$root/version" ]; then
  printf '%s' "$v" > "$root/version.tmp"
  if cmp -s "$root/version.tmp" "$root/version"; then rm -f "$root/version.tmp"; else mv "$root/version.tmp" "$root/version"; fi
fi
