// GENERATED by tools/gen-version.sh from VERSION in the Makefile. Do not edit.
// To change the version, change VERSION in the Makefile and run make.
#pragma once

/**
 * EZ-Template version macros, for libraries that support more than one
 * EZ-Template version.
 *
 * These were added in 4.0.0. EZ-Template 3.x has none of them, so your code has
 * to cope with them being missing.
 *
 * Check whether an API exists (prereleases count, so 4.0.0-beta.3 passes). Include
 * EZ-Template first, then give 3.x a fallback:
 * \code{.cpp}
 * #include "EZ-Template/api.hpp"  // before the fallback below
 *
 * #ifndef EZ_TEMPLATE_VERSION_AT_LEAST
 * #define EZ_TEMPLATE_VERSION_AT_LEAST(major, minor, patch) 0  // 3.x
 * #endif
 *
 * #if EZ_TEMPLATE_VERSION_AT_LEAST(4, 0, 0)
 *   // 4.0 or newer
 * #else
 *   // 3.x
 * #endif
 * \endcode
 *
 * Don't write "#if defined(EZ_TEMPLATE_VERSION_MAJOR) && EZ_TEMPLATE_VERSION_AT_LEAST(4, 0, 0)".
 * The preprocessor still parses the second half on 3.x, where that macro doesn't
 * exist, and stops with a syntax error.
 *
 * Check for an exact version, including the prerelease stage. Same idea, so nest the #if:
 * \code{.cpp}
 * #ifdef EZ_TEMPLATE_VERSION
 * #if EZ_TEMPLATE_VERSION >= EZ_TEMPLATE_VERSION_ENCODE(4, 0, 0, EZ_TEMPLATE_STAGE_RC, 1)
 *   // 4.0.0-rc.1 or newer
 * #endif
 * #endif
 * \endcode
 *
 * Alpha, beta and rc releases are not final. APIs can change or be removed between
 * them, and the final release may differ from any prerelease. EZ_TEMPLATE_VERSION_AT_LEAST
 * is true on every prerelease of that version, so if your code depends on something that
 * changed during the prereleases, compare against a specific stage as above. To be told
 * when you are building against a prerelease:
 * \code{.cpp}
 * #ifdef EZ_TEMPLATE_VERSION_STAGE
 * #if EZ_TEMPLATE_VERSION_STAGE != EZ_TEMPLATE_STAGE_RELEASE
 * #warning "Built against an EZ-Template prerelease, the API may change"
 * #endif
 * #endif
 * \endcode
 *
 * Print it:
 * \code{.cpp}
 * printf("EZ-Template %s\n", EZ_TEMPLATE_VERSION_STRING);
 * \endcode
 *
 * Stages sort alpha < beta < rc < release, so 4.0.0-rc.1 < 4.0.0.
 * Minor, patch and the prerelease number must stay under 100.
 */

#define EZ_TEMPLATE_STAGE_ALPHA 0
#define EZ_TEMPLATE_STAGE_BETA 1
#define EZ_TEMPLATE_STAGE_RC 2
#define EZ_TEMPLATE_STAGE_RELEASE 3

#define EZ_TEMPLATE_VERSION_MAJOR 4
#define EZ_TEMPLATE_VERSION_MINOR 0
#define EZ_TEMPLATE_VERSION_PATCH 0
#define EZ_TEMPLATE_VERSION_STAGE EZ_TEMPLATE_STAGE_BETA
#define EZ_TEMPLATE_VERSION_PRERELEASE_NUM 3  // 0 on a full release
#define EZ_TEMPLATE_VERSION_PRERELEASE "beta.3"  // "" on a full release
#define EZ_TEMPLATE_VERSION_STRING "4.0.0-beta.3"

// One integer that sorts correctly, alpha < beta < rc < release.
#define EZ_TEMPLATE_VERSION_ENCODE(major, minor, patch, stage, num) \
  ((major) * 10000000L + (minor) * 100000L + (patch) * 1000L + (stage) * 100L + (num))
#define EZ_TEMPLATE_VERSION                                                  \
  EZ_TEMPLATE_VERSION_ENCODE(EZ_TEMPLATE_VERSION_MAJOR, EZ_TEMPLATE_VERSION_MINOR, \
                             EZ_TEMPLATE_VERSION_PATCH, EZ_TEMPLATE_VERSION_STAGE, \
                             EZ_TEMPLATE_VERSION_PRERELEASE_NUM)

// Feature check. Ignores prerelease, so 4.0.0-beta.3 counts as 4.0.0.
#define EZ_TEMPLATE_VERSION_AT_LEAST(major, minor, patch)                    \
  (EZ_TEMPLATE_VERSION >= EZ_TEMPLATE_VERSION_ENCODE(major, minor, patch, EZ_TEMPLATE_STAGE_ALPHA, 0))
